import { Div } from "@/pages/create";

export const presetOne: Div[] = [
  {
    uuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
    uiElementType: "container",
    name: "container 1",
    display: "flex",
    containedElements: [
      {
        uuid: "c7675e86-d56d-467a-b009-606e184af1d6",
        uiElementType: "label",
        name: "label 4",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Main Menu",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 195,
          height: 39,
        },
        backgroundColor: "#2a9d8f",
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
      {
        uuid: "c8136dca-834d-4b6f-9d4b-679b63f4274e",
        uiElementType: "button",
        name: "button 13",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "add+",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "",
        actionType: "Count",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
        actionTypeCount: {
          setterDivUuid: "c8136dca-834d-4b6f-9d4b-679b63f4274e",
          setterDivName: "button 13",
          targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
          targetDivName: "label 5",
          count: 0,
          type: "add",
        },
      },
      {
        uuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
        uiElementType: "button",
        name: "button 14",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "sub-",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "",
        actionType: "Count",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
        actionTypeCount: {
          setterDivUuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
          setterDivName: "button 14",
          targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
          targetDivName: "label 5",
          count: 0,
          type: "subtract",
        },
      },
      {
        uuid: "7e5d8886-31bd-4af1-946f-c230a96e8dea",
        uiElementType: "button",
        name: "button 6",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Open Link",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "https://www.decentraland.org",
        actionType: "Open Link",
      },
      {
        uuid: "e7b7085d-9801-4ade-aac7-ce237d476912",
        uiElementType: "container",
        name: "container 2",
        display: "flex",
        containedElements: [
          {
            uuid: "f01d6d63-f40b-45ab-82d6-4b1ed18fa666",
            uiElementType: "button",
            name: "button 6",
            display: "flex",
            containedElements: [],
            containerName: "e7b7085d-9801-4ade-aac7-ce237d476912",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "Accept",
            fontSize: 18,
            fontFamily: "sans-serif",
            size: {
              width: 136.5,
              height: 39,
            },
            textColor: "#FFFFFF",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            backgroundColor: "#e76f51",
            backgroundImage: "",
            onMouseDown: "",
            actionType: "Show/Hide",
            actionTypeShow: {
              setterDivUuid: "f01d6d63-f40b-45ab-82d6-4b1ed18fa666",
              setterDivName: "button 6",
              targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
              targetDivName: "container 1",
              show: true,
            },
          },
          {
            uuid: "52648967-14c0-4e11-ab55-067808976425",
            uiElementType: "button",
            name: "button 7",
            display: "flex",
            containedElements: [],
            containerName: "e7b7085d-9801-4ade-aac7-ce237d476912",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "Cancel",
            fontSize: 18,
            fontFamily: "sans-serif",
            size: {
              width: 136.5,
              height: 39,
            },
            textColor: "#FFFFFF",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            backgroundColor: "#e76f51",
            backgroundImage: "",
            onMouseDown: "",
            actionType: "Show/Hide",
            actionTypeShow: {
              setterDivUuid: "52648967-14c0-4e11-ab55-067808976425",
              setterDivName: "button 7",
              targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
              targetDivName: "container 1",
              show: true,
            },
          },
        ],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "New UI container 2",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 292.5,
          height: 39,
        },
        backgroundColor: "#264653",
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "space-between",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 70.3125,
      y: 22.22222222222222,
    },
    text: "New UI container 1",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 351,
      height: 390,
    },
    backgroundColor: "#264653",
    textColor: "#000000",
    lock: false,
    flexDirection: "column",
    justifyContent: "space-around",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "52648967-14c0-4e11-ab55-067808976425",
      setterDivName: "button 7",
      targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
    uiElementType: "container",
    name: "container 3",
    display: "flex",
    containedElements: [
      {
        uuid: "d7af7c6b-b078-46c8-b3d3-4af421732f06",
        uiElementType: "label",
        name: "label 5",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Socials",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 78,
          height: 39,
        },
        backgroundColor: "#264653",
        textColor: "#e9c46a",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
      {
        uuid: "80ab8345-b3ef-4550-bd74-d9646e599d9b",
        uiElementType: "social",
        name: "social 10",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/instagram_color.png",
        backgroundImageFileName: "instagram_color.png",
        onMouseDown: "https://instagram.com/",
        actionType: "Open Link",
      },
      {
        uuid: "204b8073-b4ae-4680-a9f7-3adb42781cb4",
        uiElementType: "social",
        name: "social 11",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/facebook.png",
        backgroundImageFileName: "facebook.png",
        onMouseDown: "https://facebook.com/",
        actionType: "Open Link",
      },
      {
        uuid: "80163ee2-6a41-4dd9-be06-195eacffbaf0",
        uiElementType: "social",
        name: "social 12",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/twitter.png",
        backgroundImageFileName: "twitter.png",
        onMouseDown: "https://twitter.com/",
        actionType: "Open Link",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 71.875,
      y: 80.55555555555556,
    },
    text: "New UI container 3",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 312,
      height: 58.5,
    },
    backgroundColor: "#264653",
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "space-around",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
      setterDivName: "button 9",
      targetDivUuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
      targetDivName: "container 3",
      show: true,
    },
  },
  {
    uuid: "a0f3baee-b03a-4db6-a5c0-3b058cb1e024",
    uiElementType: "button",
    name: "button 8",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 70.3125,
      y: 91.66666666666666,
    },
    text: "show/hide 1",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 136.5,
      height: 39,
    },
    textColor: "#FFFFFF",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#2a9d8f",
    backgroundImage: "",
    onMouseDown: "",
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "a0f3baee-b03a-4db6-a5c0-3b058cb1e024",
      setterDivName: "button 8",
      targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
    uiElementType: "button",
    name: "button 9",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 87.5,
      y: 91.66666666666666,
    },
    text: "show/hide 2",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 136.5,
      height: 39,
    },
    textColor: "#FFFFFF",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#2a9d8f",
    backgroundImage: "",
    onMouseDown: "",
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
      setterDivName: "button 9",
      targetDivUuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
      targetDivName: "container 3",
      show: true,
    },
  },
  {
    uuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
    uiElementType: "label",
    name: "label 5",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 82.8125,
      y: 91.66666666666666,
    },
    text: "New UI label 5",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 39,
      height: 39,
    },
    backgroundColor: "#264653",
    textColor: "#e9c46a",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Count",
    actionTypeCount: {
      setterDivUuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
      setterDivName: "button 14",
      targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
      targetDivName: "label 5",
      count: 0,
      type: "subtract",
    },
  },
];

export const presetTwo: Div[] = [
  {
    uuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
    uiElementType: "container",
    name: "container 5",
    display: "flex",
    containedElements: [
      {
        uuid: "50d7d6d3-418a-44ad-9df9-3c74b412eabe",
        uiElementType: "label",
        name: "label 1",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "DCL UI Design Studio",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 514.8,
          height: 62.4,
        },
        backgroundColor: "#ffffff",
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
        backgroundImage: "/presets/one/label.png",
        backgroundImageFileName: "label.png",
      },
      {
        uuid: "311c4af3-fe3a-4fe0-ada6-a6852ec773f2",
        uiElementType: "container",
        name: "container 2",
        display: "flex",
        containedElements: [
          {
            uuid: "6fa20a01-3ecd-4314-bda9-e082586ed3a9",
            uiElementType: "label",
            name: "label 4",
            display: "flex",
            containedElements: [],
            containerName: "311c4af3-fe3a-4fe0-ada6-a6852ec773f2",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "DCL UI Design Studio: an open sourced web app enabling anyone to design interactive UIs for DCL scenes without coding. This drag-and-drop platform simplifies UI creation, enhancing accessibility and efficiency for creators.",
            fontSize: 18,
            fontFamily: "sans-serif",
            size: {
              width: 468,
              height: 156,
            },
            backgroundColor: "",
            textColor: "#000000",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 25,
              right: 25,
              bottom: 25,
              left: 25,
            },
            actionType: "None",
          },
        ],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "New UI container 2",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 514.8,
          height: 296.4,
        },
        backgroundColor: "#ffffff",
        textColor: "#000000",
        lock: false,
        flexDirection: "column",
        justifyContent: "center",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
        backgroundImage: "/presets/one/containerLarge.png",
        backgroundImageFileName: "containerLarge.png",
        hasSprite: false,
      },
      {
        uuid: "59b44a31-b110-4b7f-b4cb-a95a6c95a949",
        uiElementType: "button",
        name: "button 3",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "www.uistudio.app",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 442,
          height: 78,
        },
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/one/button.png",
        backgroundImageFileName: "button.png",
        onMouseDown: "https://uistudio.app/",
        actionType: "Open Link",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
      },
      {
        uuid: "2f9cd903-a8af-40a6-b9be-e9abddb70cc6",
        uiElementType: "button",
        name: "button 4",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "www.github.com/szilardjanko/ui-design-studio",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 442,
          height: 78,
        },
        textColor: "#ffffff",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/one/button.png",
        onMouseDown: "https://github.com/szilardjanko/ui-design-studio",
        actionType: "Open Link",
        backgroundImageFileName: "button.png",
        backgroundImageSize: {
          width: 238,
          height: 33,
        },
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 28.75,
      y: 4.444444444444444,
    },
    text: "New UI container 5",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 545.9999999999999,
      height: 530.4,
    },
    backgroundColor: "",
    textColor: "#000000",
    lock: false,
    flexDirection: "column",
    justifyContent: "space-between",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
      setterDivName: "button 2",
      targetDivUuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
      targetDivName: "container 5",
      show: true,
    },
  },
  {
    uuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
    uiElementType: "button",
    name: "button 2",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 77.08333333333333,
      y: 92.59259259259258,
    },
    text: "Toggle Menu",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 280.79999999999995,
      height: 46.8,
    },
    textColor: "#ffffff",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/one/button.png",
    onMouseDown: "",
    actionType: "Show/Hide",
    backgroundImageFileName: "button.png",
    backgroundImageSize: {
      width: 238,
      height: 33,
    },
    actionTypeShow: {
      setterDivUuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
      setterDivName: "button 2",
      targetDivUuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
      targetDivName: "container 5",
      show: true,
    },
  },
];

export const presetThree: Div[] = [
  {
    uuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
    uiElementType: "container",
    name: "container 1",
    display: "flex",
    containedElements: [
      {
        uuid: "692e9d6d-e8ca-41df-a572-e6a7dd1f3dee",
        uiElementType: "label",
        name: "label 2",
        display: "flex",
        containedElements: [],
        containerName: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "DCL UI Design Studio: an open sourced web app enabling anyone to design interactive UIs for DCL scenes without coding. This drag-and-drop platform simplifies UI creation, enhancing accessibility and efficiency for creators.",
        fontSize: 18,
        fontFamily: "sans-serif",
        size: {
          width: 208,
          height: 234,
        },
        backgroundColor: "",
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 100,
          right: 0,
          bottom: 0,
          left: 100,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 66.25,
      y: 4.444444444444445,
    },
    text: "New UI container 1",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 405.59999999999997,
      height: 608.4,
    },
    backgroundColor: "#ffffff",
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    backgroundImage: "/presets/two/scroll.png",
    backgroundImageFileName: "scroll.png",
    backgroundImageSize: {
      width: 545,
      height: 816,
    },
    actionTypeShow: {
      setterDivUuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
      setterDivName: "button 2",
      targetDivUuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
    uiElementType: "button",
    name: "button 2",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 91.25,
      y: 91.11111111111111,
    },
    text: "",
    fontSize: 18,
    fontFamily: "sans-serif",
    size: {
      width: 100,
      height: 50,
    },
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/two/tab.png",
    onMouseDown: "",
    actionType: "Show/Hide",
    backgroundImageFileName: "tab.png",
    backgroundImageSize: {
      width: 200,
      height: 96,
    },
    actionTypeShow: {
      setterDivUuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
      setterDivName: "button 2",
      targetDivUuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
      targetDivName: "container 1",
      show: true,
    },
  },
];

export const presetFour: Div[] = [
  {
    lock: false,
    name: "container 1",
    size: {
      width: 494,
      height: 598,
    },
    text: "New UI container 1",
    uuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
    margin: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    display: "flex",
    padding: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    flexWrap: "nowrap",
    fontSize: 18,
    position: {
      x: 60.41666666666666,
      y: 7.4074074074074066,
    },
    textColor: "#000000",
    actionType: "Show/Hide",
    alignItems: "center",
    fontFamily: "sans-serif",
    alignContent: "center",
    positionType: "absolute",
    containerName: "",
    flexDirection: "column",
    uiElementType: "container",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/three/medieval-menu.png",
    containedElements: [
      {
        lock: false,
        name: "label 3",
        size: {
          width: 390,
          height: 78,
        },
        text: "Main Menu",
        uuid: "f9e17d58-705a-47f7-bf19-aecfc1bd4928",
        margin: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 18,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#FFFFFF",
        actionType: "None",
        alignItems: "center",
        fontFamily: "sans-serif",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "label",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/three/medieval-button-3.png",
        containedElements: [],
        backgroundImageSize: {
          width: 299,
          height: 59,
        },
        backgroundImageFileName: "medieval-button-3.png",
      },
      {
        lock: false,
        name: "button 3",
        size: {
          width: 390,
          height: 78,
        },
        text: "Decentraland",
        uuid: "45b85fad-94cb-4f27-8ba6-bb18397cd7ab",
        margin: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 18,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#000000",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://www.decentraland.org",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/three/medieval-button-2.png",
        containedElements: [],
        backgroundImageSize: {
          width: 299,
          height: 59,
        },
        backgroundImageFileName: "medieval-button-2.png",
      },
      {
        lock: false,
        name: "button 4",
        size: {
          width: 390,
          height: 78,
        },
        text: "Marketplace",
        uuid: "b48d4fdb-a424-42ec-8f1c-792b8c06a083",
        margin: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 18,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#000000",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://decentraland.org/marketplace",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/three/medieval-button-2.png",
        containedElements: [],
        backgroundImageSize: {
          width: 299,
          height: 59,
        },
        backgroundImageFileName: "medieval-button-2.png",
      },
      {
        lock: false,
        name: "button 5",
        size: {
          width: 390,
          height: 78,
        },
        text: "Governance",
        uuid: "9b0ad8ff-68eb-4a55-9c17-b50f4f83e64f",
        margin: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 18,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#000000",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://decentraland.org/governance/",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/three/medieval-button-2.png",
        containedElements: [],
        backgroundImageSize: {
          width: 299,
          height: 59,
        },
        backgroundImageFileName: "medieval-button-2.png",
      },
    ],
    backgroundImageSize: {
      width: 473,
      height: 576,
    },
    backgroundImageFileName: "medieval-menu.png",
    actionTypeShow: {
      setterDivUuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
      setterDivName: "button 2",
      targetDivUuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    lock: false,
    name: "button 2",
    size: {
      width: 130,
      height: 52,
    },
    text: "Open/Close",
    uuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
    margin: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    display: "flex",
    padding: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    flexWrap: "nowrap",
    fontSize: 12,
    position: {
      x: 75.625,
      y: 91.66666666666667,
    },
    textColor: "#FFFFFF",
    actionType: "Show/Hide",
    alignItems: "center",
    fontFamily: "sans-serif",
    onMouseDown: "",
    alignContent: "center",
    positionType: "absolute",
    containerName: "",
    flexDirection: "row",
    uiElementType: "button",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/three/medieval-button.png",
    containedElements: [],
    backgroundImageSize: {
      width: 291,
      height: 100,
    },
    backgroundImageFileName: "medieval-button.png",
    actionTypeShow: {
      setterDivUuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
      setterDivName: "button 2",
      targetDivUuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
      targetDivName: "container 1",
      show: true,
    },
  },
];

export const presetFive: Div[] = [
  {
    uuid: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
    uiElementType: "container",
    name: "container 1",
    display: "flex",
    containedElements: [
      {
        uuid: "b0aea066-5e30-4f43-970c-f61847593020",
        uiElementType: "label",
        name: "label 2",
        display: "flex",
        containedElements: [],
        containerName: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Menu",
        size: {
          width: 156,
          height: 26,
        },
        backgroundColor: "#31572c",
        textColor: "#FFFFFF",
        fontSize: 15,
        fontFamily: "sans-serif",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
      {
        uuid: "b203fa30-dbcf-4419-8502-5df90de50ea9",
        uiElementType: "button",
        name: "button 3",
        display: "flex",
        containedElements: [],
        containerName: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Decentraland",
        size: {
          width: 156,
          height: 26,
        },
        textColor: "#132a13",
        fontSize: 15,
        fontFamily: "sans-serif",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ecf39e",
        backgroundImage: "",
        backgroundImageFileName: "",
        onMouseDown: "https://www.decentraland.org",
        actionType: "Open Link",
      },
      {
        uuid: "f60c833d-7a4e-4323-a3ad-8dd6321acc49",
        uiElementType: "button",
        name: "button 4",
        display: "flex",
        containedElements: [],
        containerName: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Marketplace",
        size: {
          width: 156,
          height: 26,
        },
        textColor: "#132a13",
        fontSize: 15,
        fontFamily: "sans-serif",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ecf39e",
        backgroundImage: "",
        backgroundImageFileName: "",
        onMouseDown: "https://decentraland.org/marketplace",
        actionType: "Open Link",
      },
      {
        uuid: "2153d982-8298-4ce8-87d1-9dbbb0dc99e4",
        uiElementType: "button",
        name: "button 5",
        display: "flex",
        containedElements: [],
        containerName: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Governance",
        size: {
          width: 156,
          height: 26,
        },
        textColor: "#132a13",
        fontSize: 15,
        fontFamily: "sans-serif",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ecf39e",
        backgroundImage: "",
        backgroundImageFileName: "",
        onMouseDown: "https://decentraland.org/governance/",
        actionType: "Open Link",
      },
      {
        uuid: "5ba674cd-c1fd-4834-a9d0-9e8cdc1c7afd",
        uiElementType: "button",
        name: "button 6",
        display: "flex",
        containedElements: [],
        containerName: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Close",
        size: {
          width: 156,
          height: 26,
        },
        textColor: "#132a13",
        fontSize: 15,
        fontFamily: "sans-serif",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#90a955",
        backgroundImage: "",
        backgroundImageFileName: "",
        onMouseDown: "",
        actionType: "Show/Hide",
        actionTypeShow: {
          setterDivUuid: "5ba674cd-c1fd-4834-a9d0-9e8cdc1c7afd",
          setterDivName: "button 6",
          targetDivUuid: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
          targetDivName: "container 1",
          show: true,
        },
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 81.24999999999999,
      y: 55.55555555555555,
    },
    text: "New UI container 1",
    size: {
      width: 208,
      height: 286,
    },
    backgroundColor: "#132a13",
    textColor: "#000000",
    fontSize: 18,
    fontFamily: "sans-serif",
    lock: false,
    flexDirection: "column",
    justifyContent: "space-evenly",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "5ba674cd-c1fd-4834-a9d0-9e8cdc1c7afd",
      setterDivName: "button 6",
      targetDivUuid: "048e85ea-b093-4f42-aeb6-ef3959ec0a74",
      targetDivName: "container 1",
      show: true,
    },
  },
];

export const presetSix: Div[] = [
  {
    lock: false,
    name: "container 1",
    size: {
      width: 286,
      height: 572,
    },
    text: "New UI container 1",
    uuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
    margin: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    display: "flex",
    padding: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    flexWrap: "nowrap",
    fontSize: 18,
    position: {
      x: 74.99999999999999,
      y: 14.814814814814813,
    },
    textColor: "#000000",
    actionType: "Show/Hide",
    alignItems: "center",
    fontFamily: "sans-serif",
    alignContent: "center",
    positionType: "absolute",
    containerName: "",
    flexDirection: "column",
    uiElementType: "container",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/four/pro-menu.png",
    containedElements: [
      {
        lock: false,
        name: "button 3",
        size: {
          width: 208,
          height: 52,
        },
        text: "Decentraland",
        uuid: "45b85fad-94cb-4f27-8ba6-bb18397cd7ab",
        margin: {
          top: 50,
          right: 0,
          bottom: 25,
          left: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 15,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#000000",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://www.decentraland.org",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/four/pro-button.png",
        containedElements: [],
        backgroundImageSize: {
          width: 232,
          height: 54,
        },
        backgroundImageFileName: "pro-button.png",
      },
      {
        lock: false,
        name: "button 4",
        size: {
          width: 208,
          height: 52,
        },
        text: "Marketplace",
        uuid: "b48d4fdb-a424-42ec-8f1c-792b8c06a083",
        margin: {
          top: 0,
          right: 0,
          bottom: 25,
          left: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 15,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#FFFFFF",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://decentraland.org/marketplace",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/four/pro-button-2.png",
        containedElements: [],
        backgroundImageSize: {
          width: 237,
          height: 51,
        },
        backgroundImageFileName: "pro-button-2.png",
      },
      {
        lock: true,
        name: "button 5",
        size: {
          width: 208,
          height: 52,
        },
        text: "Governance",
        uuid: "9b0ad8ff-68eb-4a55-9c17-b50f4f83e64f",
        margin: {
          top: 0,
          right: 0,
          bottom: 25,
          left: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 15,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#000000",
        actionType: "Open Link",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "https://decentraland.org/governance/",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/four/pro-button.png",
        containedElements: [],
        backgroundImageSize: {
          width: 232,
          height: 54,
        },
        backgroundImageFileName: "pro-button.png",
      },
      {
        lock: false,
        name: "button 2",
        size: {
          width: 208,
          height: 52,
        },
        text: "Close",
        uuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
        margin: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        display: "flex",
        padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
        flexWrap: "nowrap",
        fontSize: 15,
        position: {
          x: 0,
          y: 0,
        },
        textColor: "#FFFFFF",
        actionType: "Show/Hide",
        alignItems: "center",
        fontFamily: "sans-serif",
        onMouseDown: "",
        alignContent: "center",
        positionType: "relative",
        containerName: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
        flexDirection: "row",
        uiElementType: "button",
        justifyContent: "flex-start",
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/four/pro-button-2.png",
        containedElements: [],
        backgroundImageSize: {
          width: 237,
          height: 51,
        },
        backgroundImageFileName: "pro-button-2.png",
        actionTypeShow: {
          setterDivUuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
          setterDivName: "button 2",
          targetDivUuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
          targetDivName: "container 1",
          show: true,
        },
      },
    ],
    backgroundImageSize: {
      width: 284,
      height: 589,
    },
    backgroundImageFileName: "pro-menu.png",
    actionTypeShow: {
      setterDivUuid: "48d07da0-c740-4284-aa76-5f63c546ee46",
      setterDivName: "button 2",
      targetDivUuid: "b148ac50-7da8-4e2f-be3f-5c03d317569e",
      targetDivName: "container 1",
      show: true,
    },
  },
];
