import { Div } from "@/pages/CreateUi";

export const presetOne: Div[] = [
  {
    uuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
    uiElementType: "container",
    name: "container 1",
    display: "flex",
    containedElements: [
      {
        uuid: "c7675e86-d56d-467a-b009-606e184af1d6",
        uiElementType: "label",
        name: "label 4",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Main Menu",
        size: {
          width: 195,
          height: 39,
        },
        backgroundColor: "#2a9d8f",
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
      {
        uuid: "c8136dca-834d-4b6f-9d4b-679b63f4274e",
        uiElementType: "button",
        name: "button 13",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "add+",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "",
        actionType: "Count",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
        actionTypeCount: {
          setterDivUuid: "c8136dca-834d-4b6f-9d4b-679b63f4274e",
          setterDivName: "button 13",
          targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
          targetDivName: "label 5",
          count: 0,
          type: "add",
        },
      },
      {
        uuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
        uiElementType: "button",
        name: "button 14",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "sub-",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "",
        actionType: "Count",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
        actionTypeCount: {
          setterDivUuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
          setterDivName: "button 14",
          targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
          targetDivName: "label 5",
          count: 0,
          type: "subtract",
        },
      },
      {
        uuid: "7e5d8886-31bd-4af1-946f-c230a96e8dea",
        uiElementType: "button",
        name: "button 6",
        display: "flex",
        containedElements: [],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Open Link",
        size: {
          width: 136.5,
          height: 39,
        },
        textColor: "#264653",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#e9c46a",
        backgroundImage: "",
        onMouseDown: "https://www.decentraland.org",
        actionType: "Open Link",
      },
      {
        uuid: "e7b7085d-9801-4ade-aac7-ce237d476912",
        uiElementType: "container",
        name: "container 2",
        display: "flex",
        containedElements: [
          {
            uuid: "f01d6d63-f40b-45ab-82d6-4b1ed18fa666",
            uiElementType: "button",
            name: "button 6",
            display: "flex",
            containedElements: [],
            containerName: "e7b7085d-9801-4ade-aac7-ce237d476912",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "Accept",
            size: {
              width: 136.5,
              height: 39,
            },
            textColor: "#FFFFFF",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            backgroundColor: "#e76f51",
            backgroundImage: "",
            onMouseDown: "",
            actionType: "Show/Hide",
            actionTypeShow: {
              setterDivUuid: "f01d6d63-f40b-45ab-82d6-4b1ed18fa666",
              setterDivName: "button 6",
              targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
              targetDivName: "container 1",
              show: true,
            },
          },
          {
            uuid: "52648967-14c0-4e11-ab55-067808976425",
            uiElementType: "button",
            name: "button 7",
            display: "flex",
            containedElements: [],
            containerName: "e7b7085d-9801-4ade-aac7-ce237d476912",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "Cancel",
            size: {
              width: 136.5,
              height: 39,
            },
            textColor: "#FFFFFF",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            backgroundColor: "#e76f51",
            backgroundImage: "",
            onMouseDown: "",
            actionType: "Show/Hide",
            actionTypeShow: {
              setterDivUuid: "52648967-14c0-4e11-ab55-067808976425",
              setterDivName: "button 7",
              targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
              targetDivName: "container 1",
              show: true,
            },
          },
        ],
        containerName: "76567c9e-716f-42ab-a7c6-0996119b2403",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "New UI container 2",
        size: {
          width: 292.5,
          height: 39,
        },
        backgroundColor: "#264653",
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "space-between",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 70.3125,
      y: 22.22222222222222,
    },
    text: "New UI container 1",
    size: {
      width: 351,
      height: 390,
    },
    backgroundColor: "#264653",
    textColor: "#000000",
    lock: false,
    flexDirection: "column",
    justifyContent: "space-around",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "52648967-14c0-4e11-ab55-067808976425",
      setterDivName: "button 7",
      targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
    uiElementType: "container",
    name: "container 3",
    display: "flex",
    containedElements: [
      {
        uuid: "d7af7c6b-b078-46c8-b3d3-4af421732f06",
        uiElementType: "label",
        name: "label 5",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "Socials",
        size: {
          width: 78,
          height: 39,
        },
        backgroundColor: "#264653",
        textColor: "#e9c46a",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
      {
        uuid: "80ab8345-b3ef-4550-bd74-d9646e599d9b",
        uiElementType: "social",
        name: "social 10",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/instagram_color.png",
        backgroundImageFileName: "instagram_color.png",
        onMouseDown: "https://instagram.com/",
        actionType: "Open Link",
      },
      {
        uuid: "204b8073-b4ae-4680-a9f7-3adb42781cb4",
        uiElementType: "social",
        name: "social 11",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/facebook.png",
        backgroundImageFileName: "facebook.png",
        onMouseDown: "https://facebook.com/",
        actionType: "Open Link",
      },
      {
        uuid: "80163ee2-6a41-4dd9-be06-195eacffbaf0",
        uiElementType: "social",
        name: "social 12",
        display: "flex",
        containedElements: [],
        containerName: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "",
        size: {
          width: 39,
          height: 39,
        },
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/uiElements/twitter.png",
        backgroundImageFileName: "twitter.png",
        onMouseDown: "https://twitter.com/",
        actionType: "Open Link",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 71.875,
      y: 80.55555555555556,
    },
    text: "New UI container 3",
    size: {
      width: 312,
      height: 58.5,
    },
    backgroundColor: "#264653",
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "space-around",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
      setterDivName: "button 9",
      targetDivUuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
      targetDivName: "container 3",
      show: true,
    },
  },
  {
    uuid: "a0f3baee-b03a-4db6-a5c0-3b058cb1e024",
    uiElementType: "button",
    name: "button 8",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 70.3125,
      y: 91.66666666666666,
    },
    text: "show/hide 1",
    size: {
      width: 136.5,
      height: 39,
    },
    textColor: "#FFFFFF",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#2a9d8f",
    backgroundImage: "",
    onMouseDown: "",
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "a0f3baee-b03a-4db6-a5c0-3b058cb1e024",
      setterDivName: "button 8",
      targetDivUuid: "76567c9e-716f-42ab-a7c6-0996119b2403",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
    uiElementType: "button",
    name: "button 9",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 87.5,
      y: 91.66666666666666,
    },
    text: "show/hide 2",
    size: {
      width: 136.5,
      height: 39,
    },
    textColor: "#FFFFFF",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#2a9d8f",
    backgroundImage: "",
    onMouseDown: "",
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "6fad0d4d-312f-400a-b36c-0538ff5417f7",
      setterDivName: "button 9",
      targetDivUuid: "45eb3f88-6bdb-4ab7-8db6-edbeaaf4cbad",
      targetDivName: "container 3",
      show: true,
    },
  },
  {
    uuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
    uiElementType: "label",
    name: "label 5",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 82.8125,
      y: 91.66666666666666,
    },
    text: "New UI label 5",
    size: {
      width: 39,
      height: 39,
    },
    backgroundColor: "#264653",
    textColor: "#e9c46a",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Count",
    actionTypeCount: {
      setterDivUuid: "029ff691-3893-4fad-b8cd-aa788dc97f53",
      setterDivName: "button 14",
      targetDivUuid: "9bee89e5-7bcc-44c1-83ac-2213d23843ba",
      targetDivName: "label 5",
      count: 0,
      type: "subtract",
    },
  },
];

export const presetTwo: Div[] = [
  {
    uuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
    uiElementType: "container",
    name: "container 5",
    display: "flex",
    containedElements: [
      {
        uuid: "50d7d6d3-418a-44ad-9df9-3c74b412eabe",
        uiElementType: "label",
        name: "label 1",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "DCL UI Design Studio",
        size: {
          width: 514.8,
          height: 62.4,
        },
        backgroundColor: "#ffffff",
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
        backgroundImage: "/presets/one/label.png",
        backgroundImageFileName: "label.png",
      },
      {
        uuid: "311c4af3-fe3a-4fe0-ada6-a6852ec773f2",
        uiElementType: "container",
        name: "container 2",
        display: "flex",
        containedElements: [
          {
            uuid: "6fa20a01-3ecd-4314-bda9-e082586ed3a9",
            uiElementType: "label",
            name: "label 4",
            display: "flex",
            containedElements: [],
            containerName: "311c4af3-fe3a-4fe0-ada6-a6852ec773f2",
            positionType: "relative",
            position: {
              x: 0,
              y: 0,
            },
            text: "DCL UI Design Studio: an open sourced web app enabling anyone to design interactive UIs for DCL scenes without coding. This drag-and-drop platform simplifies UI creation, enhancing accessibility and efficiency for creators.",
            size: {
              width: 468,
              height: 156,
            },
            backgroundColor: "",
            textColor: "#000000",
            lock: false,
            flexDirection: "row",
            justifyContent: "flex-start",
            alignContent: "center",
            alignItems: "center",
            flexWrap: "nowrap",
            margin: {
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            },
            padding: {
              top: 25,
              right: 25,
              bottom: 25,
              left: 25,
            },
            actionType: "None",
          },
        ],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "New UI container 2",
        size: {
          width: 514.8,
          height: 296.4,
        },
        backgroundColor: "#ffffff",
        textColor: "#000000",
        lock: false,
        flexDirection: "column",
        justifyContent: "space-evenly",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
        backgroundImage: "/presets/one/containerLarge.png",
        backgroundImageFileName: "containerLarge.png",
        hasSprite: false,
      },
      {
        uuid: "59b44a31-b110-4b7f-b4cb-a95a6c95a949",
        uiElementType: "button",
        name: "button 3",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "www.ui-design-studio.vercel.app",
        size: {
          width: 389.99999999999994,
          height: 62.39999999999999,
        },
        textColor: "#FFFFFF",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/one/button.png",
        backgroundImageFileName: "button.png",
        onMouseDown: "https://ui-design-studio.vercel.app/",
        actionType: "Open Link",
        actionTypeShow: {
          setterDivUuid: "",
          setterDivName: "",
          targetDivUuid: "",
          targetDivName: "",
          show: true,
        },
      },
      {
        uuid: "2f9cd903-a8af-40a6-b9be-e9abddb70cc6",
        uiElementType: "button",
        name: "button 4",
        display: "flex",
        containedElements: [],
        containerName: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "www.github.com/szilardjanko/ui-design-studio",
        size: {
          width: 389.99999999999994,
          height: 62.39999999999999,
        },
        textColor: "#ffffff",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        backgroundColor: "#ffffff",
        backgroundImage: "/presets/one/button.png",
        onMouseDown: "https://github.com/szilardjanko/ui-design-studio",
        actionType: "Open Link",
        backgroundImageFileName: "button.png",
        backgroundImageSize: {
          width: 238,
          height: 33,
        },
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 28.75,
      y: 4.444444444444444,
    },
    text: "New UI container 5",
    size: {
      width: 530.4,
      height: 514.8,
    },
    backgroundColor: "",
    textColor: "#000000",
    lock: false,
    flexDirection: "column",
    justifyContent: "space-between",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    actionType: "Show/Hide",
    actionTypeShow: {
      setterDivUuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
      setterDivName: "button 2",
      targetDivUuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
      targetDivName: "container 5",
      show: true,
    },
  },
  {
    uuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
    uiElementType: "button",
    name: "button 2",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 77.5,
      y: 93.33333333333331,
    },
    text: "Toggle Menu",
    size: {
      width: 280.79999999999995,
      height: 46.8,
    },
    textColor: "#ffffff",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/one/button.png",
    onMouseDown: "",
    actionType: "Show/Hide",
    backgroundImageFileName: "button.png",
    backgroundImageSize: {
      width: 238,
      height: 33,
    },
    actionTypeShow: {
      setterDivUuid: "95e36df2-b5eb-49c4-b84b-1f078406dc9c",
      setterDivName: "button 2",
      targetDivUuid: "ac7a8b1d-9903-40c7-a4b1-a93ad9b2557f",
      targetDivName: "container 5",
      show: true,
    },
  },
];

export const presetThree: Div[] = [
  {
    uuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
    uiElementType: "container",
    name: "container 1",
    display: "flex",
    containedElements: [
      {
        uuid: "692e9d6d-e8ca-41df-a572-e6a7dd1f3dee",
        uiElementType: "label",
        name: "label 2",
        display: "flex",
        containedElements: [],
        containerName: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
        positionType: "relative",
        position: {
          x: 0,
          y: 0,
        },
        text: "DCL UI Design Studio: an open sourced web app enabling anyone to design interactive UIs for DCL scenes without coding. This drag-and-drop platform simplifies UI creation, enhancing accessibility and efficiency for creators.",
        size: {
          width: 202.79999999999998,
          height: 218.4,
        },
        backgroundColor: "",
        textColor: "#000000",
        lock: false,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        padding: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        actionType: "None",
      },
    ],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 66.25,
      y: 4.444444444444445,
    },
    text: "New UI container 1",
    size: {
      width: 405.59999999999997,
      height: 608.4,
    },
    backgroundColor: "#ffffff",
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 80,
      right: 0,
      bottom: 0,
      left: 100,
    },
    actionType: "Show/Hide",
    backgroundImage: "/presets/two/scroll.png",
    backgroundImageFileName: "scroll.png",
    backgroundImageSize: {
      width: 545,
      height: 816,
    },
    actionTypeShow: {
      setterDivUuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
      setterDivName: "button 2",
      targetDivUuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
      targetDivName: "container 1",
      show: true,
    },
  },
  {
    uuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
    uiElementType: "button",
    name: "button 2",
    display: "flex",
    containedElements: [],
    containerName: "",
    positionType: "absolute",
    position: {
      x: 91.25,
      y: 91.11111111111111,
    },
    text: "",
    size: {
      width: 100,
      height: 50,
    },
    textColor: "#000000",
    lock: false,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "center",
    alignItems: "center",
    flexWrap: "nowrap",
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    backgroundColor: "#ffffff",
    backgroundImage: "/presets/two/tab.png",
    onMouseDown: "",
    actionType: "Show/Hide",
    backgroundImageFileName: "tab.png",
    backgroundImageSize: {
      width: 200,
      height: 96,
    },
    actionTypeShow: {
      setterDivUuid: "6df0dd35-0b38-44b8-a2a0-2a2f2765480e",
      setterDivName: "button 2",
      targetDivUuid: "fe592e66-b594-4cf2-8b4f-3601b576ff77",
      targetDivName: "container 1",
      show: true,
    },
  },
];
